# Generated by Django 5.2.7 on 2025-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_socios', '0002_socio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='identificacion',
            field=models.CharField(db_index=True, help_text='DNI, Cédula o ID de Socio', max_length=15, unique=True),
        ),
    ]
