# Generated by Django 5.2.7 on 2025-11-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_autores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, help_text='ISBN-13 (13 caracteres)', max_length=13, null=True, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='gestion_autores.autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
