# Generated by Django 5.2.9 on 2025-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, help_text='Género literario del libro', max_length=100, null=True),
        ),
    ]
