# Generated by Django 5.2.7 on 2025-12-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0002_libro_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('REPARACION', 'En reparación'), ('PERDIDO', 'Perdido')], default='DISPONIBLE', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='gestion_libros.libro')),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
                'ordering': ['libro', 'codigo'],
            },
        ),
    ]
