# Generated by Django 5.2.7 on 2025-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0004_eliminar_campo_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('REPARACION', 'En reparación'), ('PERDIDO', 'Perdido')], db_index=True, default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
