# Generated by Django 5.2.7 on 2025-12-07 23:23

import django.db.models.deletion
from django.db import migrations, models


def migrar_libros_a_ejemplares(apps, schema_editor):
    """
    Migra los préstamos existentes de Libro a Ejemplar.
    Para cada préstamo, crea un ejemplar asociado al libro si no existe.
    """
    Prestamo = apps.get_model('gestion_prestamos', 'Prestamo')
    Ejemplar = apps.get_model('gestion_libros', 'Ejemplar')
    Libro = apps.get_model('gestion_libros', 'Libro')
    
    for prestamo in Prestamo.objects.all():
        # Obtener el libro del préstamo (aún existe en este punto)
        libro = prestamo.libro
        
        # Buscar o crear un ejemplar para este libro
        ejemplar, created = Ejemplar.objects.get_or_create(
            libro=libro,
            defaults={
                'codigo': f'EJ-{libro.id}-{prestamo.id}',
                'estado': 'PRESTADO' if prestamo.estado == 'PENDIENTE' else 'DISPONIBLE',
                'ubicacion': '',
            }
        )
        
        # Asignar el ejemplar al préstamo
        prestamo.ejemplar = ejemplar
        prestamo.save()


def revertir_migracion(apps, schema_editor):
    """
    Función de reversión: asigna el libro del ejemplar al préstamo.
    """
    Prestamo = apps.get_model('gestion_prestamos', 'Prestamo')
    
    for prestamo in Prestamo.objects.all():
        if prestamo.ejemplar:
            prestamo.libro = prestamo.ejemplar.libro
            prestamo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0003_ejemplar'),
        ('gestion_prestamos', '0001_initial'),
    ]

    operations = [
        # Primero agregar el campo ejemplar como nullable
        migrations.AddField(
            model_name='prestamo',
            name='ejemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='gestion_libros.ejemplar'),
        ),
        # Migrar los datos
        migrations.RunPython(migrar_libros_a_ejemplares, revertir_migracion),
        # Ahora eliminar el campo libro
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
        # Finalmente, hacer el campo ejemplar no-nullable
        migrations.AlterField(
            model_name='prestamo',
            name='ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='gestion_libros.ejemplar'),
        ),
    ]
