# Generated by Django 5.2.7 on 2025-12-08 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0003_ejemplar'),
        ('gestion_prestamos', '0002_cambiar_libro_a_ejemplar'),
        ('gestion_socios', '0002_socio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion_libros.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion_socios.socio')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
