# Generated by Django 5.2.7 on 2025-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0003_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_esperada',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
