# Generated by Django 5.2.7 on 2025-12-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0005_alter_ejemplar_codigo_alter_ejemplar_estado_and_more'),
        ('gestion_prestamos', '0004_alter_prestamo_estado_and_more'),
        ('gestion_socios', '0003_alter_socio_email_alter_socio_identificacion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['socio', 'estado'], name='gestion_pre_socio_i_ce530d_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['libro', 'estado'], name='gestion_pre_libro_i_2b3495_idx'),
        ),
    ]
